"""Update Post model

Revision ID: 1bcaf05e03b8
Revises: b9bef4b99735
Create Date: 2025-01-22 13:55:52.508530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bcaf05e03b8'
down_revision = 'b9bef4b99735'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gregorian_death_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('hebrew_year', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('hebrew_month', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('hebrew_day', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('hebrew_day')
        batch_op.drop_column('hebrew_month')
        batch_op.drop_column('hebrew_year')
        batch_op.drop_column('gregorian_death_date')

    # ### end Alembic commands ###
